export const flashSales = [
  {
    id: "1",
    title: "Karia blo ping backpack",
    category: "Backpack travel",
    price: 59,
    oldPrice: 69,
    rating: 4.4,
    reviews: "320k",
    image: require("@/assets/images/watch1.png"),
  },
  {
    id: "2",
    title: "Erliana blo ping backpack",
    category: "Backpack travel",
    price: 55,
    discount: "50% off",
    oldPrice: 69,
    rating: 4.3,
    reviews: "320k",
    image: require("@/assets/images/wallet1.png"),
  },
  {
    id: "3",
    title: "Erliana blo ping backpack",
    category: "Backpack travel",
    price: 55,
    discount: "50% off",
    oldPrice: 69,
    rating: 4.3,
    reviews: "320k",
    image: require("@/assets/images/handbag.png"),
  },
  {
    id: "4",
    title: "Erliana blo ping backpack",
    category: "Backpack travel",
    price: 55,
    discount: "50% off",
    oldPrice: 69,
    rating: 4.3,
    reviews: "320k",
    image: require("@/assets/images/shoe5.png"),
  },
  {
    id: "5",
    title: "Erliana blo ping backpack",
    category: "Backpack travel",
    price: 55,
    discount: "50% off",
    oldPrice: 69,
    rating: 4.3,
    reviews: "320k",
    image: require("@/assets/images/dress.png"),
  },
];

export const recommendations = [
  {
    id: "1",
    title: "Karia backpack",
    category: "Backpack, travel",
    price: 59,
    rating: 4.4,
    reviews: 120,
    image: require("@/assets/images/backpack1.png"),
    favorite: true,
  },
  {
    id: "2",
    title: "Eliana backpack",
    category: "Backpack, travel",
    price: 70,
    rating: 4.6,
    reviews: 90,
    image: require("@/assets/images/backpack1.png"),
    favorite: false,
  },
  {
    id: "3",
    title: "Geria backpack",
    category: "Backpack, travel",
    price: 77,
    rating: 4.2,
    reviews: 102,
    image: require("@/assets/images/backpack1.png"),
    favorite: false,
  },
];

export const Stores = [
  {
    id: "1",
    title: "Zara Store",
    category: "Bags",
    rating: 4.4,
    image: require("@/assets/images/backpack1.png"),
    favorite: true,
  },
  {
    id: "2",
    title: "Gucci Store",
    category: "Fashion",
    rating: 4.4,
    image: require("@/assets/images/dress.png"),
    favorite: true,
  },
  {
    id: "3",
    title: "Topman Store",
    category: "Shoes",
    rating: 4.4,
    image: require("@/assets/images/shoe5.png"),
    favorite: true,
  },
  {
    id: "4",
    title: "Deon Store",
    category: "Groceries",
    rating: 4.4,
    image: require("@/assets/images/handbag.png"),
    favorite: true,
  },
  {
    id: "5",
    title: "Wheel Store",
    category: "Cars",
    rating: 4.4,
    image: require("@/assets/images/watch1.png"),
    favorite: true,
  },
];

export const PopularProducts = [
  {
    id: "1",
    title: "Karia blo ping backpack",
    category: "Backpack travel",
    price: 59,
    rating: 4.4,
    reviews: "320k",
    image: require("@/assets/images/handbag.png"),
  },
  {
    id: "2",
    title: "Zara",
    category: "Slimfit shirt",
    price: 59,
    oldPrice: 69,
    rating: 4.4,
    reviews: "320k",
    image: require("@/assets/images/shoe5.png"),
  },
  {
    id: "3",
    title: "Zara",
    category: "Slimfit shirt",
    price: 59,
    oldPrice: 69,
    rating: 4.4,
    image: require("@/assets/images/wallet1.png"),
  },
  {
    id: "4",
    title: "Zara",
    category: "Slimfit shirt",
    price: 59,
    rating: 4.4,
    image: require("@/assets/images/dress.png"),
  },
];

export const markets = [
  {
    id: "1",
    title: "Campus",
    image: require("@/assets/images/shoe5.png"),
  },
  {
    id: "2",
    title: "Kejetia",
    image: require("@/assets/images/handbag.png"),
  },
  {
    id: "3",
    title: "Kanta",
    image: require("@/assets/images/watch1.png"),
  },
  {
    id: "4",
    title: "Campus",
    image: require("@/assets/images/watch1.png"),
  },
  {
    id: "5",
    title: "Tudu",
    image: require("@/assets/images/backpack1.png"),
  },
];

export const categories = [
  {
    id: "1",
    title: "Gents",
    subtitle: "All about men",
    image: require("@/assets/images/gents.png"),
  },
  {
    id: "2",
    title: "Ladies",
    subtitle: "Ladies dorm",
    image: require("@/assets/images/ladies.png"),
  },
  {
    id: "3",
    title: "Kids",
    subtitle: "Kids zone",
    image: require("@/assets/images/kids.png"),
  },
  {
    id: "4",
    title: "Sports",
    subtitle: "Sports land",
    image: require("@/assets/images/sports.png"),
  },
  {
    id: "5",
    title: "Electronics",
    subtitle: "All electronics",
    image: require("@/assets/images/headset.png"),
  },
  {
    id: "6",
    title: "Beauty",
    subtitle: "Glow world",
    image: require("@/assets/images/cosmetics.png"),
  },
  {
    id: "7",
    title: "Automobile",
    subtitle: "Vehicles land",
    image: require("@/assets/images/automotive.png"),
  },
];

export const gentsData = [
  {
    id: "1",
    title: "Classic Leather Wallet",
    category: "Accessories",
    price: 120,
    oldPrice: 150,
    rating: 4.8,
    reviews: "1.2k",
    image: require("@/assets/images/wallet1.png"),
  },
  {
    id: "2",
    title: "Men’s Analog Watch",
    category: "Watches",
    price: 250,
    oldPrice: 300,
    discount: "20% off",
    rating: 4.6,
    reviews: "980",
    image: require("@/assets/images/watch1.png"),
  },
  {
    id: "3",
    title: "Brown Leather Belt",
    category: "Accessories",
    price: 90,
    oldPrice: 110,
    rating: 4.4,
    reviews: "540",
    image: require("@/assets/images/watch1.png"),
  },
  {
    id: "4",
    title: "Formal Loafers",
    category: "Shoes",
    price: 350,
    oldPrice: 400,
    discount: "15% off",
    rating: 4.7,
    reviews: "760",
    image: require("@/assets/images/shoe5.png"),
  },
  {
    id: "5",
    title: "Men’s Sunglasses",
    category: "Eyewear",
    price: 180,
    oldPrice: 200,
    rating: 4.5,
    reviews: "1.1k",
    image: require("@/assets/images/shoe5.png"),
  },
  {
    id: "6",
    title: "Casual Denim Jacket",
    category: "Clothing",
    price: 320,
    oldPrice: 360,
    rating: 4.9,
    reviews: "1.5k",
    image: require("@/assets/images/wallet1.png"),
  },
  {
    id: "7",
    title: "Men’s Backpack",
    category: "Bags",
    price: 280,
    oldPrice: 320,
    discount: "10% off",
    rating: 4.3,
    reviews: "640",
    image: require("@/assets/images/backpack1.png"),
  },
  {
    id: "8",
    title: "Running Sneakers",
    category: "Shoes",
    price: 400,
    oldPrice: 450,
    rating: 4.7,
    reviews: "880",
    image: require("@/assets/images/shoe5.png"),
  },
];

export const ladiesData = [
  {
    id: "1",
    title: "Elegant Handbag Clutch",
    category: "Bags",
    price: 150,
    oldPrice: 190,
    rating: 4.7,
    reviews: "820",
    image: require("@/assets/images/handbag.png"),
  },
  {
    id: "2",
    title: "Women’s Designer Watch",
    category: "Watches",
    price: 320,
    oldPrice: 400,
    discount: "20% off",
    rating: 4.9,
    reviews: "650",
    image: require("@/assets/images/watch1.png"),
  },
  {
    id: "3",
    title: "Gold Hoop Earrings Set",
    category: "Jewellery",
    price: 75,
    oldPrice: 95,
    rating: 4.4,
    reviews: "430",
    image: require("@/assets/images/handbag.png"),
  },
  {
    id: "4",
    title: "Formal Stiletto Heels",
    category: "Shoes",
    price: 220,
    oldPrice: 270,
    discount: "18% off",
    rating: 4.8,
    reviews: "570",
    image: require("@/assets/images/shoe5.png"),
  },
  {
    id: "5",
    title: "Silk Summer Dress",
    category: "Clothing",
    price: 180,
    oldPrice: 230,
    rating: 4.6,
    reviews: "910",
    image: require("@/assets/images/dress.png"),
  },
  {
    id: "6",
    title: "Makeup & Beauty Kit",
    category: "Beauty",
    price: 130,
    oldPrice: 155,
    rating: 4.5,
    reviews: "680",
    image: require("@/assets/images/dress.png"),
  },
  {
    id: "7",
    title: "Women’s Tote Bag",
    category: "Bags",
    price: 140,
    oldPrice: 170,
    discount: "12% off",
    rating: 4.3,
    reviews: "490",
    image: require("@/assets/images/handbag.png"),
  },
  {
    id: "8",
    title: "Casual Sneakers for Women",
    category: "Shoes",
    price: 195,
    oldPrice: 240,
    rating: 4.7,
    reviews: "730",
    image: require("@/assets/images/shoe5.png"),
  },
];

export const kidsData = [
  {
    id: "1",
    title: "Colorful Kids Backpack",
    category: "Bags",
    price: 80,
    oldPrice: 100,
    rating: 4.6,
    reviews: "430",
    image: require("@/assets/images/handbag.png"),
  },
  {
    id: "2",
    title: "Boys’ Sneakers High Top",
    category: "Shoes",
    price: 95,
    oldPrice: 120,
    discount: "20% off",
    rating: 4.7,
    reviews: "540",
    image: require("@/assets/images//shoe5.png"),
  },
  {
    id: "3",
    title: "Kids’ Hoodie Sweatshirt",
    category: "Clothing",
    price: 60,
    oldPrice: 75,
    rating: 4.4,
    reviews: "310",
    image: require("@/assets/images/dress.png"),
  },
  {
    id: "4",
    title: "Girls’ Mermaid Dress",
    category: "Clothing",
    price: 70,
    oldPrice: 90,
    discount: "22% off",
    rating: 4.8,
    reviews: "390",
    image: require("@/assets/images/wallet1.png"),
  },
  {
    id: "5",
    title: "Kids’ Sunglasses Set",
    category: "Eyewear",
    price: 40,
    oldPrice: 50,
    rating: 4.5,
    reviews: "260",
    image: require("@/assets/images/backpack1.png"),
  },
  {
    id: "6",
    title: "Kids’ Smart Watch",
    category: "Watches",
    price: 110,
    oldPrice: 140,
    rating: 4.3,
    reviews: "320",
    image: require("@/assets/images/watch1.png"),
  },
  {
    id: "7",
    title: "Kids’ Winter Boots",
    category: "Shoes",
    price: 85,
    oldPrice: 105,
    discount: "15% off",
    rating: 4.6,
    reviews: "370",
    image: require("@/assets/images/shoe5.png"),
  },
  {
    id: "8",
    title: "Kids’ Puzzle & Game Set",
    category: "Toys",
    price: 45,
    oldPrice: 60,
    rating: 4.7,
    reviews: "430",
    image: require("@/assets/images/wallet1.png"),
  },
];

export const vouchers = [
  {
    id: "1",
    image: require("@/assets/images/wallet1.png"),
    amount: 100,
  },
  {
    id: "2",
    image: require("@/assets/images/wallet1.png"),
    amount: 100,
  },
  {
    id: "3",
    image: require("@/assets/images/wallet1.png"),
    amount: 100,
  },
  {
    id: "4",
    image: require("@/assets/images/wallet1.png"),
    amount: 100,
  },
  {
    id: "5",
    image: require("@/assets/images/wallet1.png"),
    amount: 100,
  },
];
