import { AppColors } from "@/constants/Colors";

export type ThemeColors = {
  screen: string;
  card: string;
  cardBorder: string;
  text: string;
  textMuted: string;
  textSecondary: string;
  textBody: string;
  header: string;
  headerBorder: string;
  surface: string;
  surfaceMuted: string;
  surfaceSubtle: string;
  border: string;
  borderStrong: string;
  segmentBg: string;
  segmentActive: string;
  pill: string;
  pillText: string;
  inputBg: string;
  inputBorder: string;
  placeholder: string;
  iconMuted: string;
  tabBar: string;
  tabBarBorder: string;
  tabFocused: string;
  shadow: string;
  backdrop: string;
  primary: string;
  onPrimary: string;
  inverseText: string;
  editAvatarBorder: string;
  imagePlaceholder: string;
  cardElevated: string;
  skeleton: string;
  skeletonHighlight: string;
  dangerSoft: string;
  dangerText: string;
  successSoft: string;
  successBorder: string;
  successText: string;
  warningSoft: string;
  warningBorder: string;
  warningText: string;
  infoSoft: string;
  infoBorder: string;
  infoText: string;
  ratingSoft: string;
  ratingBorder: string;
  ratingText: string;
  accentSoft: string;
  inverseSurface: string;
  onInverseSurface: string;
  mutedOnInverse: string;
  bottomBar: string;
  bottomBarBorder: string;
  overlayControl: string;
  link: string;
};

export const lightTheme: ThemeColors = {
  screen: "#F5F7FA",
  card: "#FFFFFF",
  cardBorder: "#E6EAF0",
  text: AppColors.text,
  textMuted: "#6B7280",
  textSecondary: "#4B5563",
  textBody: "#374151",
  header: AppColors.white,
  headerBorder: "#E5E7EB",
  surface: "#FFFFFF",
  surfaceMuted: "#F1F3F5",
  surfaceSubtle: "#F8FAFC",
  border: "#E5E7EB",
  borderStrong: "#E6EAF0",
  segmentBg: "#EEF2F6",
  segmentActive: "#FFFFFF",
  pill: "#F3F4F6",
  pillText: "#4B5563",
  inputBg: "#F8FAFC",
  inputBorder: "#E5E7EB",
  placeholder: "#9CA3AF",
  iconMuted: "#9CA3AF",
  tabBar: AppColors.white,
  tabBarBorder: "#E5E7EB",
  tabFocused: "#E5E7EB",
  shadow: "#0F172A",
  backdrop: "rgba(15, 23, 42, 0.45)",
  primary: AppColors.primary,
  onPrimary: "#FFFFFF",
  inverseText: "#FFFFFF",
  editAvatarBorder: "#FFFFFF",
  imagePlaceholder: "#F3F4F6",
  cardElevated: "#F8FAFC",
  skeleton: "#E8ECF1",
  skeletonHighlight: "rgba(255,255,255,0.55)",
  dangerSoft: "#FEF2F2",
  dangerText: "#DC2626",
  successSoft: "#F0FDF4",
  successBorder: "#BBF7D0",
  successText: "#059669",
  warningSoft: "#FFFBEB",
  warningBorder: "#FDE68A",
  warningText: "#B45309",
  infoSoft: "#EEF2FF",
  infoBorder: "#C7D2FE",
  infoText: "#4338CA",
  ratingSoft: "#FFFBEB",
  ratingBorder: "#F3D28A",
  ratingText: "#B45309",
  accentSoft: "#F8FAFC",
  inverseSurface: "#0F172A",
  onInverseSurface: "#F8FAFC",
  mutedOnInverse: "#CBD5E1",
  bottomBar: "rgba(255,255,255,0.985)",
  bottomBarBorder: "#E5E7EB",
  overlayControl: "#F2F2F2",
  link: AppColors.primary,
};

export const darkTheme: ThemeColors = {
  screen: "#0A0E17",
  card: "#131A29",
  cardBorder: "#1F2A3D",
  text: "#F4F6FA",
  textMuted: "#94A3B8",
  textSecondary: "#CBD5E1",
  textBody: "#E2E8F0",
  header: "#0F1522",
  headerBorder: "#243044",
  surface: "#131A29",
  surfaceMuted: "#182030",
  surfaceSubtle: "#151D2C",
  border: "#243044",
  borderStrong: "#2D3B52",
  segmentBg: "#182030",
  segmentActive: "#243044",
  pill: "#182030",
  pillText: "#CBD5E1",
  inputBg: "#151D2C",
  inputBorder: "#2D3B52",
  placeholder: "#64748B",
  iconMuted: "#94A3B8",
  tabBar: "#0F1522",
  tabBarBorder: "#243044",
  tabFocused: "#2D3B52",
  shadow: "#000000",
  backdrop: "rgba(0, 0, 0, 0.72)",
  primary: "#8E8E8E",
  onPrimary: "#FFFFFF",
  inverseText: "#FFFFFF",
  editAvatarBorder: "#131A29",
  imagePlaceholder: "#182030",
  cardElevated: "#182030",
  skeleton: "#1E293B",
  skeletonHighlight: "rgba(255,255,255,0.06)",
  dangerSoft: "#3B1519",
  dangerText: "#FCA5A5",
  successSoft: "#0F2419",
  successBorder: "#166534",
  successText: "#34D399",
  warningSoft: "#2A2010",
  warningBorder: "#854D0E",
  warningText: "#FCD34D",
  infoSoft: "#151E33",
  infoBorder: "#3730A3",
  infoText: "#A5B4FC",
  ratingSoft: "#2A2010",
  ratingBorder: "#854D0E",
  ratingText: "#FCD34D",
  accentSoft: "#182030",
  inverseSurface: "#243044",
  onInverseSurface: "#F4F6FA",
  mutedOnInverse: "#94A3B8",
  bottomBar: "#131A29",
  bottomBarBorder: "#243044",
  overlayControl: "#182030",
  link: "#CBD5E1",
};

export const THEME_STORAGE_KEY = "odos_dark_mode";
export const THEME_PREFERENCE_KEY = "odos_theme_preference";
