export const GHANA_REGIONS = [
  "Ahafo",
  "Ashanti",
  "Bono",
  "Bono East",
  "Central",
  "Eastern",
  "Greater Accra",
  "North East",
  "Northern",
  "Oti",
  "Savannah",
  "Upper East",
  "Upper West",
  "Volta",
  "Western",
  "Western North",
] as const;

export type GhanaRegion = (typeof GHANA_REGIONS)[number];

export const GHANA_REGION_CITIES: Record<GhanaRegion, string[]> = {
  "Greater Accra": [
    "Accra",
    "Tema",
    "Ashaiman",
    "Madina",
    "Adenta",
    "Nungua",
    "Teshie",
    "Lashibi",
    "Dome",
    "Gbawe",
    "Dodowa",
    "Kasoa",
    "La",
    "Osu",
    "East Legon",
    "Spintex",
    "Kaneshie",
    "Achimota",
    "Weija",
    "Pokuase",
    "Amasaman",
    "Ablekuma",
    "Kpone",
    "Sakumono",
    "Tema New Town",
    "Mallam",
    "Haatso",
    "Legon",
    "Dansoman",
    "Teshie-Nungua",
  ],
  Ashanti: [
    "Kumasi",
    "Obuasi",
    "Ejura",
    "Mampong",
    "Konongo",
    "Agogo",
    "Bekwai",
    "Asokwa",
    "Suame",
    "Juaben",
    "Offinso",
    "Nsuta",
    "Effiduase",
    "Tafo",
    "Atonsu",
    "Bantama",
    "Manhyia",
    "Asawase",
    "Fomena",
    "New Edubiase",
    "Jacobu",
    "Tepa",
    "Manso Nkwanta",
    "Nkawie",
    "Kuntanase",
    "Ejisu",
    "Afigya-Kwabre",
    "Bosome Freho",
    "Bekwai Municipal",
    "Kumawu",
  ],
  Central: [
    "Cape Coast",
    "Elmina",
    "Winneba",
    "Kasoa",
    "Agona Swedru",
    "Saltpond",
    "Dunkwa-on-Offin",
    "Mankessim",
    "Apam",
    "Twifo Praso",
    "Assin Foso",
    "Breman Asikuma",
    "Abura Dunkwa",
    "Ajumako",
    "Anomabu",
    "Moree",
    "Komenda",
    "Dawurampong",
    "Bawjiase",
    "Gomoa Fetteh",
    "Nsaba",
    "Bisease",
    "Abakrampa",
    "Pedu",
    "Kakumdo",
    "Swedru",
    "Buduburam",
    "Odupong Kpehe",
    "Nsuaem",
    "Abura-Asebu-Kwamankese",
  ],
  Eastern: [
    "Koforidua",
    "Nkawkaw",
    "Akim Oda",
    "Nsawam",
    "Suhum",
    "Kibi",
    "Akwatia",
    "Aburi",
    "Mpraeso",
    "Begoro",
    "Akim Swedru",
    "Asamankese",
    "Akim Tafo",
    "Donkorkrom",
    "Kade",
    "Akosombo",
    "Somanya",
    "Odumase Krobo",
    "Kpong",
    "Adukrom",
    "New Abirem",
    "Akim Ofoase",
    "Akim Bosome",
    "Akim Manso",
    "Akim Achiase",
    "Kwabeng",
    "Akim Wenchi",
    "Akyemansa",
    "Birim Central",
    "Birim North",
  ],
  Volta: [
    "Ho",
    "Hohoe",
    "Keta",
    "Aflao",
    "Kpando",
    "Sogakope",
    "Anloga",
    "Denu",
    "Dzodze",
    "Akatsi",
    "Abor",
    "Adaklu",
    "Ave",
    "Adidome",
    "Adafienu",
    "Agortime",
    "Agotime Akpo",
    "Ave Dakpa",
    "Battor",
    "Fume",
    "Have",
    "Mepe",
    "Nkwanta",
    "Peki",
    "Ve Golokwati",
    "Worawora",
    "Jasikan",
    "Kadjebi",
    "Krachi",
    "Biakoye",
  ],
  Northern: [
    "Tamale",
    "Yendi",
    "Savelugu",
    "Bimbilla",
    "Gushegu",
    "Karaga",
    "Kpandai",
    "Saboba",
    "Chereponi",
    "Zabzugu",
    "Tatale",
    "Nanton",
    "Tolon",
    "Kumbungu",
    "Sagnarigu",
    "Mion",
    "Nanumba North",
    "Nanumba South",
    "East Mamprusi",
    "West Mamprusi",
    "Bunkpurugu",
    "Nakpanduri",
    "Wulensi",
    "Salaga",
    "Buipe",
    "Daboya",
    "Mankarigu",
    "Sakogu",
    "Gambaga",
    "Walewale",
  ],
  "Upper East": [
    "Bolgatanga",
    "Bawku",
    "Navrongo",
    "Zebilla",
    "Sandema",
    "Bongo",
    "Paga",
    "Fumbisi",
    "Garu",
    "Tempane",
    "Binduri",
    "Tongo",
    "Nangodi",
    "Zuarungu",
    "Widnaba",
    "Chiana",
    "Pusiga",
    "Kongo",
    "Talensi",
    "Nabdam",
    "Builsa North",
    "Builsa South",
    "Kassena Nankana",
    "Kassena Nankana West",
    "Bawku West",
    "Bawku Municipal",
    "Bolgatanga Municipal",
    "Bongo District",
    "Garu-Tempane",
    "Binduri District",
    "Pusiga District",
  ],
  "Upper West": [
    "Wa",
    "Tumu",
    "Lawra",
    "Nandom",
    "Jirapa",
    "Nadowli",
    "Daffiama",
    "Bussie",
    "Hamile",
    "Funsi",
    "Wechiau",
    "Lambussie",
    "Issa",
    "Kaleo",
    "Babile",
    "Charikpong",
    "Dorimon",
    "Gwollu",
    "Kperisi",
    "Sissala East",
    "Sissala West",
    "Wa East",
    "Wa Municipal",
    "Wa West",
    "Jirapa Municipal",
    "Lawra Municipal",
    "Nandom Municipal",
    "Nadowli Kaleo",
    "Lambussie Karni",
    "Daffiama Bussie Issa",
  ],
  Western: [
    "Sekondi",
    "Takoradi",
    "Tarkwa",
    "Axim",
    "Prestea",
    "Bogoso",
    "Elubo",
    "Half Assini",
    "Shama",
    "Effiakuma",
    "Kojokrom",
    "New Takoradi",
    "Essikado",
    "Kwesimintsim",
    "Agona Nkwanta",
    "Dixcove",
    "Busua",
    "Princess Town",
    "Nkroful",
    "Akwidaa",
    "Beyin",
    "Mpohor",
    "Daboase",
    "Aboso",
    "Huni Valley",
    "Wassa Akropong",
    "Asankragua",
    "Enchi",
    "Juaboso",
    "Ahanta West",
  ],
  "Western North": [
    "Sefwi Wiawso",
    "Bibiani",
    "Juaboso",
    "Enchi",
    "Asankragua",
    "Adabokrom",
    "Bodi",
    "Awaso",
    "Sefwi Akontombra",
    "Sefwi Debiso",
    "Sefwi Domenase",
    "Sefwi Juaboso",
    "Bia East",
    "Bia West",
    "Suaman",
    "Aowin Municipal",
    "Bibiani Anhwiaso Bekwai",
    "Sefwi Wiawso Municipal",
    "Juaboso Municipal",
    "Bodi Municipal",
    "Sefwi Akontombra Municipal",
    "Sefwi Debiso Municipal",
    "Sefwi Domenase Municipal",
    "Sefwi Juaboso Municipal",
    "Bia East Municipal",
    "Bia West Municipal",
    "Suaman District",
    "Aowin District",
    "Bibiani Municipal",
    "Sefwi Wiawso District",
  ],
  Ahafo: [
    "Goaso",
    "Bechem",
    "Hwidiem",
    "Kukuom",
    "Duayaw Nkwanta",
    "Kenyasi",
    "Mim",
    "Tepa",
    "Nsawkaw",
    "Acherensua",
    "Kwasu",
    "Akrodie",
    "Asutifi North",
    "Asutifi South",
    "Tano North",
    "Tano South",
    "Asunafo North",
    "Asunafo South",
    "Goaso Municipal",
    "Bechem Municipal",
    "Hwidiem Municipal",
    "Kukuom Municipal",
    "Duayaw Nkwanta Municipal",
    "Kenyasi Municipal",
    "Mim Municipal",
    "Tepa Municipal",
    "Nsawkaw Municipal",
    "Acherensua Municipal",
    "Kwasu Municipal",
    "Akrodie Municipal",
  ],
  Bono: [
    "Sunyani",
    "Berekum",
    "Dormaa Ahenkro",
    "Wenchi",
    "Nsoatre",
    "Odumase",
    "Fiapre",
    "Chiraa",
    "Drobo",
    "Sampa",
    "Jinijini",
    "Nkrankwanta",
    "Banda Ahenkro",
    "Bui",
    "Dormaa West",
    "Dormaa East",
    "Jaman North",
    "Jaman South",
    "Sunyani Municipal",
    "Sunyani West",
    "Berekum Municipal",
    "Berekum East",
    "Dormaa Central",
    "Wenchi Municipal",
    "Nsoatre Municipal",
    "Odumase Municipal",
    "Fiapre Municipal",
    "Chiraa Municipal",
    "Drobo Municipal",
    "Sampa Municipal",
  ],
  "Bono East": [
    "Techiman",
    "Kintampo",
    "Nkoranza",
    "Atebubu",
    "Kwame Danso",
    "Prang",
    "Yeji",
    "Tuobodom",
    "Jema",
    "Busunya",
    "Amantin",
    "Kajaji",
    "Akumadan",
    "Buipe",
    "Kintampo North",
    "Kintampo South",
    "Nkoranza North",
    "Nkoranza South",
    "Pru East",
    "Pru West",
    "Sene East",
    "Sene West",
    "Techiman Municipal",
    "Techiman North",
    "Atebubu Amantin",
    "Kintampo Municipal",
    "Nkoranza Municipal",
    "Pru East Municipal",
    "Pru West Municipal",
    "Sene East Municipal",
    "Sene West Municipal",
  ],
  Oti: [
    "Dambai",
    "Jasikan",
    "Kadjebi",
    "Krachi",
    "Nkwanta",
    "Kpassa",
    "Kete Krachi",
    "Chinderi",
    "Banda",
    "Brewaniase",
    "Worawora",
    "Kpandai",
    "Salaga",
    "Bimbilla",
    "Guan",
    "Biakoye",
    "Jasikan Municipal",
    "Kadjebi Municipal",
    "Krachi East",
    "Krachi West",
    "Krachi Nchumuru",
    "Nkwanta North",
    "Nkwanta South",
    "Krachi West Municipal",
    "Krachi East Municipal",
    "Krachi Nchumuru Municipal",
    "Nkwanta North Municipal",
    "Nkwanta South Municipal",
    "Dambai Municipal",
    "Biakoye Municipal",
  ],
  Savannah: [
    "Damongo",
    "Bole",
    "Sawla",
    "Larabanga",
    "Daboya",
    "Mankarigu",
    "Buipe",
    "Salaga",
    "Kpandai",
    "Bimbilla",
    "Gushegu",
    "Karaga",
    "Yendi",
    "Savelugu",
    "Tamale",
    "Tolon",
    "Kumbungu",
    "Sagnarigu",
    "Mion",
    "Nanumba North",
    "Nanumba South",
    "East Mamprusi",
    "West Mamprusi",
    "Bunkpurugu",
    "Nakpanduri",
    "Wulensi",
    "Salaga Municipal",
    "Bole Municipal",
    "Sawla Tuna Kalba",
    "West Gonja",
  ],
  "North East": [
    "Nalerigu",
    "Gambaga",
    "Walewale",
    "Bunkpurugu",
    "Chereponi",
    "Yunyoo",
    "Nabdam",
    "Talensi",
    "Bolgatanga",
    "Bawku",
    "Navrongo",
    "Zebilla",
    "Sandema",
    "Bongo",
    "Paga",
    "Fumbisi",
    "Garu",
    "Tempane",
    "Binduri",
    "Tongo",
    "Nangodi",
    "Zuarungu",
    "Widnaba",
    "Chiana",
    "Pusiga",
    "Kongo",
    "Bawku West",
    "Talensi District",
    "Nabdam District",
    "East Mamprusi Municipal",
    "West Mamprusi Municipal",
  ],
};

function normalizeLookupValue(value: string) {
  return value.trim().toLowerCase().replace(/\s+/g, " ");
}

export function matchGhanaRegion(value: string): GhanaRegion | null {
  const normalized = normalizeLookupValue(value);
  if (!normalized) {
    return null;
  }

  return (
    GHANA_REGIONS.find((region) => normalizeLookupValue(region) === normalized) ??
    GHANA_REGIONS.find((region) => normalized.includes(normalizeLookupValue(region))) ??
    null
  );
}

export function getCitiesForRegion(region: string, currentCity?: string): string[] {
  const matchedRegion = matchGhanaRegion(region);
  if (!matchedRegion) {
    return currentCity?.trim() ? [currentCity.trim()] : [];
  }

  const cities = [...GHANA_REGION_CITIES[matchedRegion]];
  const trimmedCurrent = currentCity?.trim();
  if (
    trimmedCurrent &&
    !cities.some((city) => normalizeLookupValue(city) === normalizeLookupValue(trimmedCurrent))
  ) {
    cities.unshift(trimmedCurrent);
  }

  return cities;
}

export function matchCityInRegion(region: string, city: string): string | null {
  const trimmedCity = city.trim();
  if (!trimmedCity) {
    return null;
  }

  const cities = getCitiesForRegion(region);
  return (
    cities.find((item) => normalizeLookupValue(item) === normalizeLookupValue(trimmedCity)) ??
    trimmedCity
  );
}
