import { AppColors } from "@/constants/Colors";
import type { ThemeColors } from "@/constants/theme";
import Fonts from "@/constants/Fonts";
import { rMS, rS, rV } from "@/styles/responsive";
import { Dimensions, StyleSheet } from "react-native";

const screenWidth = Dimensions.get("window").width;

export function createProductDetailStyles(c: ThemeColors) {
  return StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: c.screen,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: c.header,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: c.headerBorder,
    paddingBottom: rV(12),
  },
  headerButton: {
    width: rMS(40),
    height: rMS(40),
    borderRadius: rMS(20),
    backgroundColor: c.surfaceMuted,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    flex: 1,
    textAlign: "center",
    marginHorizontal: rS(12),
    fontSize: rMS(17),
    fontFamily: Fonts.titleBold,
    color: c.text,
  },
  scroll: {
    flex: 1,
  },
  heroSection: {
    position: "relative",
    paddingBottom: rV(10),
  },
  heroBackdrop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: rV(250),
    backgroundColor: c.cardElevated,
    borderBottomLeftRadius: rMS(34),
    borderBottomRightRadius: rMS(34),
  },
  galleryShell: {
    position: "relative",
    backgroundColor: c.imagePlaceholder,
    marginHorizontal: rS(16),
    marginTop: rV(12),
    borderRadius: rMS(30),
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.7)",
  },
  imageSlide: {
    width: screenWidth - rS(32),
    height: rV(350),
    backgroundColor: c.imagePlaceholder,
  },
  heroImage: {
    width: "100%",
    height: "100%",
  },
  galleryOverlayRow: {
    position: "absolute",
    top: rV(16),
    left: rS(16),
    right: rS(16),
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  galleryCountBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: rS(6),
    backgroundColor: "rgba(15, 23, 42, 0.62)",
    paddingHorizontal: rS(12),
    paddingVertical: rV(8),
    borderRadius: 999,
  },
  galleryCountText: {
    color: c.onInverseSurface,
    fontSize: rMS(11),
    fontFamily: Fonts.title,
  },
  discountPill: {
    backgroundColor: "rgba(15, 23, 42, 0.78)",
    paddingHorizontal: rS(12),
    paddingVertical: rV(8),
    borderRadius: 999,
  },
  discountPillText: {
    color: c.onInverseSurface,
    fontSize: rMS(11),
    fontFamily: Fonts.titleBold,
  },
  expandHintWrap: {
    position: "absolute",
    right: rS(16),
    bottom: rV(16),
    flexDirection: "row",
    alignItems: "center",
    gap: rS(6),
    backgroundColor: "rgba(15, 23, 42, 0.62)",
    paddingHorizontal: rS(12),
    paddingVertical: rV(8),
    borderRadius: 999,
  },
  expandHintText: {
    color: c.onInverseSurface,
    fontSize: rMS(11),
    fontFamily: Fonts.title,
  },
  thumbnailWrap: {
    width: rMS(64),
    height: rMS(64),
    borderRadius: rMS(16),
    marginRight: rS(10),
    padding: 3,
    backgroundColor: c.card,
    borderWidth: 1,
    borderColor: c.border,
  },
  thumbnailWrapActive: {
    borderColor: AppColors.primary,
    borderWidth: 2,
  },
  thumbnailImage: {
    width: "100%",
    height: "100%",
    borderRadius: rMS(13),
  },
  content: {
    paddingTop: rV(10),
  },
  infoShell: {
    backgroundColor: c.card,
    borderRadius: rMS(28),
    paddingHorizontal: rS(18),
    paddingVertical: rV(18),
    borderWidth: 1,
    borderColor: c.border,
    shadowColor: c.shadow,
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 22,
    elevation: 3,
  },
  taxonomyRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: rS(8),
  },
  taxonomyPill: {
    borderRadius: 999,
    backgroundColor: c.pill,
    paddingHorizontal: rS(12),
    paddingVertical: rV(7),
  },
  taxonomyPillText: {
    fontSize: rMS(11),
    color: c.text,
    fontFamily: Fonts.title,
  },
  productTitle: {
    marginTop: rV(14),
    fontSize: rMS(26),
    lineHeight: rMS(33),
    color: c.text,
    fontFamily: Fonts.titleBold,
  },
  productLead: {
    marginTop: rV(10),
    fontSize: rMS(13),
    lineHeight: rMS(20),
    color: c.textMuted,
    fontFamily: Fonts.text,
  },
  metaRow: {
    marginTop: rV(14),
    flexDirection: "row",
    flexWrap: "wrap",
    gap: rS(10),
  },
  infoStatsRow: {
    flexDirection: "row",
    gap: rS(10),
    marginTop: rV(16),
  },
  infoStat: {
    flex: 1,
    backgroundColor: c.accentSoft,
    borderRadius: rMS(16),
    paddingHorizontal: rS(12),
    paddingVertical: rV(12),
    borderWidth: 1,
    borderColor: c.border,
  },
  infoStatLabel: {
    fontSize: rMS(10.5),
    color: c.textMuted,
    fontFamily: Fonts.text,
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  infoStatValue: {
    marginTop: rV(6),
    fontSize: rMS(12),
    color: c.text,
    fontFamily: Fonts.title,
  },
  metaChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: rS(6),
    backgroundColor: c.card,
    borderRadius: 999,
    paddingHorizontal: rS(12),
    paddingVertical: rV(8),
    borderWidth: 1,
    borderColor: c.border,
  },
  metaChipText: {
    fontSize: rMS(11),
    color: c.textMuted,
    fontFamily: Fonts.text,
  },
  priceCard: {
    marginTop: rV(18),
    borderRadius: rMS(26),
    backgroundColor: c.inverseSurface,
    padding: rS(18),
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.04)",
    shadowColor: c.shadow,
    shadowOpacity: 0.12,
    shadowOffset: { width: 0, height: 12 },
    shadowRadius: 26,
    elevation: 4,
  },
  priceTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: rS(12),
  },
  priceLabel: {
    fontSize: rMS(12),
    color: c.mutedOnInverse,
    fontFamily: Fonts.text,
  },
  priceRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: rV(6),
    flexWrap: "wrap",
  },
  price: {
    fontSize: rMS(24),
    color: c.onInverseSurface,
    fontFamily: Fonts.titleBold,
  },
  oldPrice: {
    marginLeft: rS(10),
    fontSize: rMS(15),
    color: c.placeholder,
    fontFamily: Fonts.text,
    textDecorationLine: "line-through",
  },
  savingsPill: {
    alignSelf: "flex-start",
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.1)",
    paddingHorizontal: rS(12),
    paddingVertical: rV(8),
  },
  savingsPillText: {
    fontSize: rMS(11),
    color: "#E2E8F0",
    fontFamily: Fonts.titleBold,
  },
  variantCard: {
    marginTop: rV(18),
    borderRadius: rMS(24),
    backgroundColor: c.card,
    padding: rS(18),
    borderWidth: 1,
    borderColor: c.border,
    gap: rV(14),
  },
  variantHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  variantTitle: {
    fontSize: rMS(14),
    color: c.text,
    fontFamily: Fonts.titleBold,
  },
  variantValue: {
    fontSize: rMS(12),
    color: c.textMuted,
    fontFamily: Fonts.title,
  },
  colorRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: rS(10),
  },
  colorBtn: {
    minWidth: rMS(64),
    minHeight: rMS(42),
    borderRadius: rMS(16),
    borderWidth: 1,
    borderColor: "#DBDBDB",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: c.card,
    paddingHorizontal: rS(12),
    paddingVertical: rV(9),
    gap: rS(8),
    flexDirection: "row",
  },
  colorBtnActive: {
    borderColor: AppColors.primary,
    borderWidth: 2,
    backgroundColor: c.accentSoft,
  },
  colorDot: {
    width: rMS(22),
    height: rMS(22),
    borderRadius: rMS(11),
  },
  colorLabel: {
    fontSize: rMS(12),
    color: c.text,
    fontFamily: Fonts.textBold,
  },
  sizeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: rS(8),
  },
  sizeBtn: {
    minWidth: rMS(48),
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: rS(13),
    paddingVertical: rV(9),
    borderRadius: rMS(12),
    borderWidth: 1,
    borderColor: "#D6D6D8",
    backgroundColor: c.card,
  },
  sizeBtnActive: {
    borderColor: AppColors.primary,
    backgroundColor: AppColors.primary,
  },
  sizeBtnText: {
    fontSize: rMS(13),
    color: c.text,
    fontFamily: Fonts.textBold,
  },
  sizeBtnTextActive: {
    color: c.onPrimary,
  },
  storeCard: {
    marginTop: rV(18),
    borderRadius: rMS(24),
    backgroundColor: c.inverseSurface,
    padding: rS(18),
  },
  storeHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: rS(12),
  },
  storeTitleWrap: {
    flex: 1,
    flexDirection: "row",
    gap: rS(12),
  },
  storeIconWrap: {
    width: rMS(40),
    height: rMS(40),
    borderRadius: rMS(20),
    backgroundColor: "rgba(255,255,255,0.14)",
    alignItems: "center",
    justifyContent: "center",
  },
  storeEyebrow: {
    fontSize: rMS(11),
    color: c.mutedOnInverse,
    fontFamily: Fonts.text,
  },
  storeTitle: {
    marginTop: rV(2),
    fontSize: rMS(16),
    color: c.onInverseSurface,
    fontFamily: Fonts.titleBold,
  },
  storeMeta: {
    marginTop: rV(4),
    fontSize: rMS(12),
    color: c.mutedOnInverse,
    fontFamily: Fonts.text,
  },
  storeRatingPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: rS(5),
    alignSelf: "flex-start",
    backgroundColor: "rgba(255,255,255,0.12)",
    paddingHorizontal: rS(10),
    paddingVertical: rV(7),
    borderRadius: 999,
  },
  storeRatingText: {
    color: c.onInverseSurface,
    fontSize: rMS(11),
    fontFamily: Fonts.title,
  },
  storeDescription: {
    marginTop: rV(12),
    fontSize: rMS(12),
    lineHeight: rMS(18),
    color: "#DDE5EE",
    fontFamily: Fonts.text,
  },
  storeActionsRow: {
    flexDirection: "row",
    gap: rS(10),
    marginTop: rV(14),
  },
  storePrimaryAction: {
    flex: 1,
    backgroundColor: c.card,
    paddingVertical: rV(11),
    borderRadius: rMS(14),
    alignItems: "center",
  },
  storePrimaryActionText: {
    color: c.inverseSurface,
    fontSize: rMS(13),
    fontFamily: Fonts.titleBold,
  },
  storeSecondaryAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: rS(6),
    borderRadius: rMS(14),
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    paddingHorizontal: rS(14),
  },
  storeSecondaryActionText: {
    color: c.onInverseSurface,
    fontSize: rMS(12),
    fontFamily: Fonts.title,
  },
  reviewSectionWrap: {
    marginTop: rV(18),
  },
  sectionStack: {
    marginTop: rV(18),
  },
  relatedHeader: {
    marginTop: rV(24),
    marginBottom: rV(12),
  },
  relatedTitle: {
    fontSize: rMS(18),
    color: c.text,
    fontFamily: Fonts.titleBold,
  },
  relatedSubtitle: {
    marginTop: rV(4),
    fontSize: rMS(12),
    color: c.textMuted,
    fontFamily: Fonts.text,
  },
  relatedList: {
    paddingBottom: rV(4),
  },
  fullscreenModal: {
    flex: 1,
    backgroundColor: "#020617",
  },
  fullscreenHeader: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  fullscreenHeaderButton: {
    width: rMS(42),
    height: rMS(42),
    borderRadius: rMS(21),
    backgroundColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  fullscreenCounter: {
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.08)",
    paddingHorizontal: rS(14),
    paddingVertical: rV(9),
  },
  fullscreenCounterText: {
    color: c.onInverseSurface,
    fontSize: rMS(12),
    fontFamily: Fonts.title,
  },
  fullscreenImageSlide: {
    width: screenWidth,
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  fullscreenImage: {
    width: "100%",
    height: "100%",
  },
  fullscreenFooter: {
    paddingHorizontal: rS(16),
    paddingBottom: rV(22),
  },
  fullscreenTitle: {
    color: c.onInverseSurface,
    fontSize: rMS(16),
    fontFamily: Fonts.titleBold,
  },
  fullscreenPrice: {
    marginTop: rV(4),
    color: c.mutedOnInverse,
    fontSize: rMS(13),
    fontFamily: Fonts.text,
  },
  fullscreenThumbs: {
    paddingTop: rV(14),
  },
  fullscreenThumbWrap: {
    width: rMS(56),
    height: rMS(56),
    borderRadius: rMS(14),
    overflow: "hidden",
    marginRight: rS(10),
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
  },
  fullscreenThumbWrapActive: {
    borderWidth: 2,
    borderColor: AppColors.white,
  },
  fullscreenThumbImage: {
    width: "100%",
    height: "100%",
  },
  bottomBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: c.bottomBar,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: c.bottomBarBorder,
    paddingTop: rV(8),
    shadowColor: c.shadow,
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: -4 },
    shadowRadius: 12,
    elevation: 10,
  },
  bottomMainRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: rS(10),
  },
  bottomPriceBlock: {
    flex: 1,
    minWidth: 0,
    justifyContent: "center",
    gap: rV(1),
  },
  bottomPriceLabel: {
    fontSize: rMS(10.5),
    color: c.textMuted,
    fontFamily: Fonts.text,
    letterSpacing: 0.35,
    textTransform: "uppercase",
  },
  bottomPriceValue: {
    fontSize: rMS(17),
    lineHeight: rMS(21),
    color: c.text,
    fontFamily: Fonts.titleBold,
  },
  bottomPriceValueCompact: {
    fontSize: rMS(21),
    lineHeight: rMS(24),
  },
  bottomVariantText: {
    fontSize: rMS(10.5),
    lineHeight: rMS(14),
    color: c.textMuted,
    fontFamily: Fonts.text,
  },
  bottomWishlistButton: {
    width: rS(38),
    height: rS(38),
    borderRadius: rMS(12),
    backgroundColor: c.surfaceMuted,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.border,
    flexShrink: 0,
  },
  bottomActionsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: rS(8),
    flexShrink: 0,
  },
  buyNowBtn: {
    minWidth: rS(88),
    height: rS(42),
    paddingHorizontal: rS(14),
    borderRadius: rMS(12),
    backgroundColor: c.inverseSurface,
    alignItems: "center",
    justifyContent: "center",
  },
  buyNowBtnCompact: {
    minWidth: rS(88),
    paddingHorizontal: rS(10),
  },
  buyNowText: {
    color: c.onInverseSurface,
    fontSize: rMS(12.5),
    fontFamily: Fonts.titleBold,
    letterSpacing: 0.1,
  },
});
}
