import Fonts from "@/constants/Fonts";
import { useTheme } from "@/context/ThemeContext";
import { rMS, rS, rV } from "@/styles/responsive";
import { useMemo } from "react";
import { StyleSheet } from "react-native";
import type { ThemeColors } from "@/constants/theme";

export function buildCheckoutStyles(c: ThemeColors) {
  return StyleSheet.create({
    flex: { flex: 1 },
    container: {
      flex: 1,
      backgroundColor: c.screen,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: rS(16),
      paddingBottom: rV(12),
      backgroundColor: c.header,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.headerBorder,
    },
    backButton: {
      width: rMS(40),
      height: rMS(40),
      borderRadius: rMS(20),
      backgroundColor: c.overlayControl,
      alignItems: "center",
      justifyContent: "center",
    },
    headerTitle: {
      flex: 1,
      textAlign: "center",
      fontSize: rMS(18),
      fontFamily: Fonts.textBold,
      color: c.text,
    },
    headerSpacer: {
      width: rMS(40),
    },
    scroll: { flex: 1 },
    scrollContent: {
      paddingHorizontal: rS(16),
      paddingTop: rV(16),
    },
    card: {
      backgroundColor: c.card,
      borderRadius: rMS(16),
      padding: rS(16),
      marginBottom: rV(12),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.cardBorder,
    },
    sectionLabel: {
      fontSize: rMS(13),
      fontFamily: Fonts.textBold,
      color: c.textMuted,
      textTransform: "uppercase",
      letterSpacing: 0.5,
      marginBottom: rV(12),
    },
    sectionHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: rV(12),
    },
    row: {
      flexDirection: "row",
      alignItems: "flex-start",
    },
    imageWrap: {
      borderRadius: rMS(12),
      overflow: "hidden",
      backgroundColor: c.imagePlaceholder,
    },
    productImage: {
      width: rMS(88),
      height: rMS(88),
      borderRadius: rMS(12),
    },
    placeholderImage: {
      alignItems: "center",
      justifyContent: "center",
    },
    productInfo: {
      flex: 1,
      marginLeft: rS(12),
    },
    productTitle: {
      fontSize: rMS(15),
      fontFamily: Fonts.title,
      color: c.text,
      marginBottom: rV(4),
    },
    category: {
      fontSize: rMS(12),
      fontFamily: Fonts.text,
      color: c.textMuted,
      marginBottom: rV(6),
    },
    variantRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: rS(6),
      marginBottom: rV(8),
    },
    variantPill: {
      paddingHorizontal: rS(8),
      paddingVertical: rV(4),
      borderRadius: rMS(8),
      backgroundColor: c.pill,
    },
    variantPillText: {
      fontSize: rMS(11),
      fontFamily: Fonts.textBold,
      color: c.pillText,
    },
    priceRow: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: rV(10),
    },
    price: {
      fontSize: rMS(16),
      fontFamily: Fonts.textBold,
      color: c.text,
    },
    oldPrice: {
      fontSize: rMS(13),
      fontFamily: Fonts.text,
      color: c.textMuted,
      textDecorationLine: "line-through",
      marginLeft: rS(8),
    },
    quantityRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    quantityLabel: {
      fontSize: rMS(12),
      color: c.textMuted,
      fontFamily: Fonts.textBold,
    },
    quantityControls: {
      flexDirection: "row",
      alignItems: "center",
      gap: rS(10),
    },
    quantityBtn: {
      width: rMS(30),
      height: rMS(30),
      borderRadius: rMS(10),
      backgroundColor: c.surfaceMuted,
      alignItems: "center",
      justifyContent: "center",
    },
    quantityValue: {
      fontSize: rMS(14),
      color: c.text,
      fontFamily: Fonts.textBold,
      minWidth: rS(18),
      textAlign: "center",
    },
    cartSummaryList: { gap: rV(10) },
    cartSummaryRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: rS(12),
      paddingBottom: rV(10),
    },
    cartSummaryRowBorder: {
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.border,
    },
    cartSummaryText: { flex: 1 },
    cartSummaryTitle: {
      fontSize: rMS(14),
      fontFamily: Fonts.textBold,
      color: c.text,
    },
    cartSummaryMeta: {
      marginTop: rV(3),
      fontSize: rMS(12),
      fontFamily: Fonts.text,
      color: c.textMuted,
    },
    cartSummaryAmount: {
      fontSize: rMS(14),
      fontFamily: Fonts.titleBold,
      color: c.text,
    },
    deliveryRow: {
      flexDirection: "row",
      alignItems: "center",
    },
    deliveryIcon: {
      width: rMS(40),
      height: rMS(40),
      borderRadius: rMS(12),
      backgroundColor: c.infoSoft,
      alignItems: "center",
      justifyContent: "center",
      marginRight: rS(12),
    },
    deliveryText: { flex: 1 },
    deliveryTag: {
      alignSelf: "flex-start",
      marginBottom: rV(4),
      paddingHorizontal: rS(10),
      paddingVertical: rV(4),
      borderRadius: rMS(999),
      backgroundColor: c.pill,
      fontSize: rMS(11),
      fontFamily: Fonts.textBold,
      color: c.textMuted,
    },
    deliveryTitle: {
      fontSize: rMS(14),
      fontFamily: Fonts.textBold,
      color: c.text,
    },
    deliverySub: {
      marginTop: rV(4),
      fontSize: rMS(12),
      fontFamily: Fonts.text,
      color: c.textMuted,
    },
    paymentRow: {
      flexDirection: "row",
      alignItems: "center",
    },
    paymentIcon: {
      width: rMS(40),
      height: rMS(40),
      borderRadius: rMS(12),
      backgroundColor: c.infoSoft,
      alignItems: "center",
      justifyContent: "center",
      marginRight: rS(12),
    },
    paymentText: { flex: 1 },
    paymentTitle: {
      fontSize: rMS(14),
      fontFamily: Fonts.textBold,
      color: c.text,
    },
    paymentSub: {
      marginTop: rV(4),
      fontSize: rMS(12),
      fontFamily: Fonts.text,
      color: c.textMuted,
    },
    voucherBrowseBtn: {
      paddingHorizontal: rS(10),
      paddingVertical: rV(6),
      borderRadius: rMS(999),
      backgroundColor: c.pill,
    },
    voucherBrowseText: {
      fontSize: rMS(11),
      fontFamily: Fonts.textBold,
      color: c.textMuted,
    },
    voucherEntryRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: rS(10),
    },
    voucherInputWrap: {
      flex: 1,
      minHeight: rV(48),
      borderRadius: rMS(14),
      borderWidth: 1,
      borderColor: c.inputBorder,
      backgroundColor: c.inputBg,
      paddingHorizontal: rS(12),
      flexDirection: "row",
      alignItems: "center",
      gap: rS(8),
    },
    voucherInput: {
      flex: 1,
      fontSize: rMS(13),
      color: c.text,
      fontFamily: Fonts.textBold,
      letterSpacing: 0.4,
    },
    voucherApplyBtn: {
      minHeight: rV(48),
      paddingHorizontal: rS(18),
      borderRadius: rMS(14),
      backgroundColor: c.primary,
      alignItems: "center",
      justifyContent: "center",
    },
    voucherApplyBtnDisabled: { opacity: 0.7 },
    voucherApplyText: {
      fontSize: rMS(12),
      fontFamily: Fonts.textBold,
      color: c.onPrimary,
    },
    voucherHelpText: {
      marginTop: rV(10),
      fontSize: rMS(12),
      lineHeight: rMS(18),
      fontFamily: Fonts.text,
      color: c.textMuted,
    },
    suggestedVouchersWrap: { marginTop: rV(12) },
    suggestedVouchersTitle: {
      fontSize: rMS(11.5),
      fontFamily: Fonts.textBold,
      color: c.text,
      marginBottom: rV(8),
    },
    suggestedVouchersRow: {
      gap: rS(8),
      paddingRight: rS(4),
    },
    suggestedVoucherChip: {
      minWidth: rS(120),
      borderRadius: rMS(14),
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.surfaceSubtle,
      paddingHorizontal: rS(12),
      paddingVertical: rV(10),
    },
    suggestedVoucherCode: {
      fontSize: rMS(11.5),
      fontFamily: Fonts.textBold,
      color: c.textSecondary,
      letterSpacing: 0.4,
    },
    suggestedVoucherMeta: {
      marginTop: rV(4),
      fontSize: rMS(10.5),
      fontFamily: Fonts.text,
      color: c.textMuted,
    },
    voucherErrorText: {
      marginTop: rV(10),
      fontSize: rMS(12),
      fontFamily: Fonts.textBold,
      color: c.dangerText,
    },
    appliedVoucherCard: {
      marginTop: rV(12),
      borderRadius: rMS(14),
      backgroundColor: c.successSoft,
      borderWidth: 1,
      borderColor: c.successBorder,
      padding: rS(12),
    },
    appliedVoucherTopRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: rS(12),
    },
    appliedVoucherBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: rS(5),
      paddingHorizontal: rS(10),
      paddingVertical: rV(5),
      borderRadius: rMS(999),
      backgroundColor: c.successSoft,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.successBorder,
    },
    appliedVoucherBadgeText: {
      fontSize: rMS(11),
      fontFamily: Fonts.textBold,
      color: c.successText,
      letterSpacing: 0.4,
    },
    removeVoucherBtn: { paddingVertical: rV(4) },
    removeVoucherText: {
      fontSize: rMS(12),
      fontFamily: Fonts.textBold,
      color: c.dangerText,
    },
    appliedVoucherTitle: {
      marginTop: rV(10),
      fontSize: rMS(14),
      fontFamily: Fonts.title,
      color: c.text,
    },
    appliedVoucherMeta: {
      marginTop: rV(4),
      fontSize: rMS(12),
      lineHeight: rMS(18),
      fontFamily: Fonts.text,
      color: c.successText,
    },
    appliedVoucherScopeNote: {
      marginTop: rV(6),
      fontSize: rMS(11.5),
      lineHeight: rMS(17),
      fontFamily: Fonts.text,
      color: c.textMuted,
    },
    totalRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: rV(12),
    },
    totalRowLast: {
      marginBottom: 0,
      paddingTop: rV(4),
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: c.border,
    },
    totalLabel: {
      fontSize: rMS(13),
      fontFamily: Fonts.text,
      color: c.textMuted,
    },
    totalValue: {
      fontSize: rMS(13),
      fontFamily: Fonts.textBold,
      color: c.text,
    },
    totalLabelBold: {
      fontSize: rMS(15),
      fontFamily: Fonts.titleBold,
      color: c.text,
    },
    totalValueBold: {
      fontSize: rMS(16),
      fontFamily: Fonts.titleBold,
      color: c.text,
    },
    discountValue: {
      fontSize: rMS(13),
      fontFamily: Fonts.textBold,
      color: c.successText,
    },
    shippingFree: {
      color: c.successText,
    },
    footer: {
      paddingHorizontal: rS(16),
      paddingTop: rV(12),
      paddingBottom: rV(24),
      backgroundColor: c.bottomBar,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: c.bottomBarBorder,
    },
    footerHint: {
      fontSize: rMS(12),
      fontFamily: Fonts.text,
      color: c.textMuted,
      marginBottom: rV(10),
    },
    placeOrderBtn: {
      minHeight: rV(52),
      borderRadius: rMS(16),
      backgroundColor: c.primary,
      alignItems: "center",
      justifyContent: "center",
    },
    placeOrderBtnDisabled: {
      opacity: 0.55,
    },
    placeOrderText: {
      fontSize: rMS(14),
      fontFamily: Fonts.textBold,
      color: c.onPrimary,
    },
    emptyCheckout: {
      flex: 1,
      justifyContent: "center",
      paddingHorizontal: rS(24),
    },
    emptyTitle: {
      fontSize: rMS(18),
      fontFamily: Fonts.titleBold,
      color: c.text,
      textAlign: "center",
      marginBottom: rV(8),
    },
    emptyText: {
      fontSize: rMS(13),
      fontFamily: Fonts.text,
      color: c.textMuted,
      textAlign: "center",
      lineHeight: rMS(20),
    },
    emptyButton: {
      alignSelf: "center",
      marginTop: rV(18),
      paddingHorizontal: rS(18),
      paddingVertical: rV(12),
      borderRadius: rMS(14),
      backgroundColor: c.primary,
    },
    emptyButtonText: {
      fontSize: rMS(13),
      fontFamily: Fonts.textBold,
      color: c.onPrimary,
    },
  });
}

export function useCheckoutStyles() {
  const { colors } = useTheme();
  return useMemo(() => buildCheckoutStyles(colors), [colors]);
}
