import { AppColors } from "@/constants/Colors";
import Fonts from "@/constants/Fonts";
import type { ThemeColors } from "@/constants/theme";
import { useTheme } from "@/context/ThemeContext";
import { rMS, rS, rV } from "@/styles/responsive";
import { useMemo } from "react";
import { StyleSheet } from "react-native";

export function createChatStyles(c: ThemeColors) {
  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: c.screen,
    },
    screenBackground: {
      flex: 1,
    },
    loadingWrap: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      gap: rV(12),
    },
    loadingText: {
      fontFamily: Fonts.text,
      fontSize: rMS(13),
      color: c.textMuted,
    },
    threadRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: rS(12),
    },
    avatar: {
      width: rS(48),
      height: rS(48),
      borderRadius: rMS(16),
      backgroundColor: c.surfaceMuted,
    },
    avatarPlaceholder: {
      width: rS(48),
      height: rS(48),
      borderRadius: rMS(16),
      backgroundColor: c.pill,
      alignItems: "center",
      justifyContent: "center",
    },
    threadCopy: {
      flex: 1,
      gap: rV(2),
    },
    threadTop: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: rS(8),
    },
    threadName: {
      flex: 1,
      fontFamily: Fonts.titleBold,
      fontSize: rMS(14.5),
      color: c.text,
    },
    threadTime: {
      fontFamily: Fonts.text,
      fontSize: rMS(11),
      color: c.placeholder,
    },
    threadStore: {
      fontFamily: Fonts.title,
      fontSize: rMS(11.5),
      color: c.primary,
    },
    threadPreview: {
      fontFamily: Fonts.text,
      fontSize: rMS(12.5),
      color: c.textMuted,
    },
    header: {
      backgroundColor: c.card,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.headerBorder,
      paddingHorizontal: rS(16),
      paddingBottom: rV(12),
      shadowColor: c.shadow,
      shadowOpacity: 0.04,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 4 },
      elevation: 2,
    },
    headerRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: rS(12),
    },
    backButton: {
      width: rS(40),
      height: rS(40),
      borderRadius: rMS(20),
      backgroundColor: c.surfaceMuted,
      alignItems: "center",
      justifyContent: "center",
    },
    headerAvatar: {
      width: rS(44),
      height: rS(44),
      borderRadius: rMS(16),
      backgroundColor: c.surfaceMuted,
    },
    headerAvatarSupport: {
      width: rS(44),
      height: rS(44),
      borderRadius: rMS(16),
      backgroundColor: c.text,
      alignItems: "center",
      justifyContent: "center",
    },
    headerCopy: {
      flex: 1,
      gap: rV(4),
    },
    headerTitle: {
      fontFamily: Fonts.titleBold,
      fontSize: rMS(17),
      color: c.text,
    },
    headerSubtitle: {
      fontFamily: Fonts.text,
      fontSize: rMS(12),
      color: c.textMuted,
    },
    badgeRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: rS(8),
      marginTop: rV(4),
    },
    statusBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: rS(5),
      paddingHorizontal: rS(10),
      paddingVertical: rV(5),
      borderRadius: 999,
    },
    statusBadgeText: {
      fontFamily: Fonts.titleBold,
      fontSize: rMS(10.5),
    },
    contextWrap: {
      paddingHorizontal: rS(16),
      paddingTop: rV(12),
    },
    contextCard: {
      backgroundColor: c.card,
      borderRadius: rMS(20),
      paddingHorizontal: rS(14),
      paddingVertical: rV(12),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.cardBorder,
      flexDirection: "row",
      alignItems: "center",
      gap: rS(12),
    },
    contextImage: {
      width: rS(48),
      height: rS(48),
      borderRadius: rMS(14),
      backgroundColor: c.surfaceMuted,
    },
    contextCopy: {
      flex: 1,
      gap: rV(2),
    },
    contextLabel: {
      fontFamily: Fonts.titleBold,
      fontSize: rMS(10.5),
      color: c.placeholder,
      textTransform: "uppercase",
      letterSpacing: 0.6,
    },
    contextTitle: {
      fontFamily: Fonts.titleBold,
      fontSize: rMS(13.5),
      color: c.text,
    },
    contextSub: {
      fontFamily: Fonts.text,
      fontSize: rMS(12),
      color: c.textMuted,
    },
    messagesContent: {
      paddingTop: rV(8),
      paddingBottom: rV(16),
      flexGrow: 1,
    },
    messagesList: {
      flex: 1,
    },
    dayWrap: {
      alignItems: "center",
      paddingVertical: rV(10),
    },
    dayPill: {
      backgroundColor: c.border,
      paddingHorizontal: rS(12),
      paddingVertical: rV(4),
      borderRadius: 999,
    },
    dayText: {
      fontFamily: Fonts.text,
      fontSize: rMS(11),
      color: c.textSecondary,
    },
    messageRow: {
      paddingHorizontal: rS(16),
      paddingVertical: rV(3),
    },
    messageRowMine: {
      alignItems: "flex-end",
    },
    messageRowTheirs: {
      alignItems: "flex-start",
    },
    bubble: {
      maxWidth: "82%",
      paddingHorizontal: rS(14),
      paddingVertical: rV(10),
      borderTopLeftRadius: rMS(18),
      borderTopRightRadius: rMS(18),
      shadowColor: c.shadow,
      shadowOpacity: 0.05,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: 1,
    },
    bubbleMine: {
      backgroundColor: c.primary,
      borderBottomLeftRadius: rMS(18),
      borderBottomRightRadius: rMS(6),
    },
    bubbleTheirs: {
      backgroundColor: c.card,
      borderBottomLeftRadius: rMS(6),
      borderBottomRightRadius: rMS(18),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.cardBorder,
    },
    bubbleText: {
      fontFamily: Fonts.text,
      fontSize: rMS(14),
      lineHeight: rMS(20),
    },
    bubbleMeta: {
      marginTop: rV(6),
      fontFamily: Fonts.text,
      fontSize: rMS(10),
      textAlign: "right",
    },
    quickReplyRow: {
      gap: rS(8),
      paddingHorizontal: rS(16),
      paddingBottom: rV(8),
      paddingTop: rV(4),
    },
    quickReplyChip: {
      borderRadius: rMS(999),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      backgroundColor: c.card,
      paddingHorizontal: rS(14),
      paddingVertical: rV(9),
      shadowColor: c.shadow,
      shadowOpacity: 0.03,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 1,
    },
    quickReplyLabel: {
      fontFamily: Fonts.text,
      fontSize: rMS(12.5),
      color: c.textSecondary,
    },
    composerWrap: {
      backgroundColor: c.card,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: c.headerBorder,
      paddingHorizontal: rS(16),
      paddingTop: rV(12),
      shadowColor: c.shadow,
      shadowOpacity: 0.06,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: -3 },
      elevation: 8,
    },
    composerHint: {
      fontFamily: Fonts.text,
      fontSize: rMS(11),
      color: c.textMuted,
      marginBottom: rV(8),
      paddingHorizontal: rS(4),
    },
    composerRow: {
      flexDirection: "row",
      alignItems: "flex-end",
      gap: rS(10),
    },
    composerInputWrap: {
      flex: 1,
      backgroundColor: c.surfaceMuted,
      borderRadius: rMS(24),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      paddingHorizontal: rS(16),
      paddingVertical: rV(10),
      minHeight: rV(46),
      justifyContent: "center",
    },
    composerInput: {
      maxHeight: rV(110),
      padding: 0,
      fontFamily: Fonts.text,
      fontSize: rMS(14),
      lineHeight: rMS(20),
      color: c.text,
    },
    sendButton: {
      width: rS(44),
      height: rS(44),
      borderRadius: rMS(22),
      alignItems: "center",
      justifyContent: "center",
    },
    sendButtonActive: {
      backgroundColor: c.primary,
    },
    sendButtonDisabled: {
      backgroundColor: c.border,
    },
    errorBanner: {
      marginHorizontal: rS(16),
      marginTop: rV(12),
      backgroundColor: c.dangerSoft,
      borderRadius: rMS(16),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.dangerText,
      paddingHorizontal: rS(14),
      paddingVertical: rV(12),
    },
    errorText: {
      fontFamily: Fonts.text,
      fontSize: rMS(12.5),
      color: c.dangerText,
      lineHeight: rMS(18),
    },
    emptyMessages: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: rS(28),
      paddingVertical: rV(40),
      gap: rV(10),
    },
    emptyMessagesIconWrap: {
      width: rS(64),
      height: rS(64),
      borderRadius: rMS(22),
      backgroundColor: c.accentSoft,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: rV(4),
    },
    emptyMessagesTitle: {
      fontFamily: Fonts.titleBold,
      fontSize: rMS(16),
      color: c.text,
      textAlign: "center",
    },
    emptyMessagesText: {
      fontFamily: Fonts.text,
      fontSize: rMS(13),
      color: c.textMuted,
      textAlign: "center",
      lineHeight: rMS(20),
    },
    chipRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: rS(8),
      marginTop: rV(10),
    },
    chip: {
      backgroundColor: c.surfaceMuted,
      borderRadius: 999,
      paddingHorizontal: rS(10),
      paddingVertical: rV(5),
    },
    chipText: {
      fontFamily: Fonts.text,
      fontSize: rMS(11),
      color: c.textSecondary,
    },
    supportContextWrap: {
      paddingHorizontal: rS(16),
      paddingTop: rV(10),
      paddingBottom: rV(4),
    },
    supportContextCard: {
      backgroundColor: c.card,
      borderRadius: rMS(18),
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.cardBorder,
      overflow: "hidden",
    },
    supportContextHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: rS(10),
      paddingHorizontal: rS(14),
      paddingVertical: rV(12),
    },
    supportContextBody: {
      paddingHorizontal: rS(14),
      paddingBottom: rV(12),
      gap: rV(8),
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: c.border,
    },
    supportContextTitle: {
      flex: 1,
      fontFamily: Fonts.titleBold,
      fontSize: rMS(13.5),
      color: c.text,
    },
    supportContextSub: {
      fontFamily: Fonts.text,
      fontSize: rMS(12),
      color: c.textMuted,
      lineHeight: rMS(18),
    },
    copyToast: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: rV(96),
      alignItems: "center",
      zIndex: 30,
    },
    copyToastPill: {
      flexDirection: "row",
      alignItems: "center",
      gap: rS(6),
      paddingHorizontal: rS(14),
      paddingVertical: rV(8),
      borderRadius: 999,
      backgroundColor: "rgba(15, 23, 42, 0.92)",
    },
    copyToastText: {
      fontFamily: Fonts.titleBold,
      fontSize: rMS(13),
      color: "#FFFFFF",
    },
  });
}

export function useChatStyles() {
  const { colors } = useTheme();
  return useMemo(() => createChatStyles(colors), [colors]);
}
